### ISSUE TITLE
赞

### ISSUE THREAD

**Issue by longhongwei17** [BinBear/breadtrip-ReactiveCocoa-MVVM-#1]
代码风格不错

**Comment by BinBear** [comment]
O(∩_∩)O谢谢！

**Comment by BinBear** [comment]
O(∩_∩)O谢谢！

**Comment by LGByte** [comment]
your  are a coder manito,we'd like your code style  and hope to learn more with you ! @BinBear  wait for your more source code update !

**Comment by BinBear** [comment]
@AllenDongCoder thanks
