### ISSUE TITLE
请教楼主

### ISSUE THREAD

**Issue by CoderLwcXing** [BinBear/breadtrip-ReactiveCocoa-MVVM-#11]
我的还是报错 ，就是pod里面的 RealReachability  这个报错  ，我今天新下载一个还是一样报错，是否可以看下，下面是报错的信息，谢谢。我在Xcode8.3.3运行不会，Xcode9 的模拟器运行会有这个错误
In file included from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.m:50:
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:279:20: error: expected parameter declarator
check_compile_time(sizeof(ICMPHeader) == 8);
                   ^
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:279:20: error: expected ')'
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:279:19: note: to match this '('
check_compile_time(sizeof(ICMPHeader) == 8);
                  ^
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:280:20: error: expected parameter declarator
check_compile_time(offsetof(ICMPHeader, type) == 0);
                   ^
In module 'Darwin' imported from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:58:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^
In file included from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.m:50:
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:280:20: error: expected ')'
In module 'Darwin' imported from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:58:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^
In file included from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.m:50:
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:280:19: note: to match this '('
check_compile_time(offsetof(ICMPHeader, type) == 0);
                  ^
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:281:20: error: expected parameter declarator
check_compile_time(offsetof(ICMPHeader, code) == 1);
                   ^
In module 'Darwin' imported from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:58:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^
In file included from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.m:50:
/Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:281:20: error: expected ')'
In module 'Darwin' imported from /Users/l_wcx/Downloads/breadtrip-ReactiveCocoa-MVVM--master/Pods/RealReachability/RealReachability/Ping/PingFoundation.h:58:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)

**Comment by BinBear** [comment]
你 pod update一下

**Comment by CoderLwcXing** [comment]
中午  我弄好了

**Comment by CoderLwcXing** [comment]
谢谢啦
我把cocoapods 重新装了  然后pod update  就好了

**Comment by lvxiangan** [comment]
check_compile_time(sizeof(ICMPHeader) == 8);  这一段代码确实报错，没看明白代码用途，直接注释掉也能运行

**Comment by CoderLwcXing** [comment]
那是 pod 里面的  你要改？？

**Comment by lvxiangan** [comment]
不考虑升级，我认为可以改
