### ISSUE TITLE
实现的热更新

### ISSUE THREAD

**Issue by MansionWayh** [BinBear/breadtrip-ReactiveCocoa-MVVM-#2]
jspath 找不到main.js文件，执行test脚本.是怎么实现的热更新，可以在简书说明一下吗

**Comment by BinBear** [comment]
@MansionWayh 脚本是我自己在JSPatch平台下发的，你们看不到，出现这个提示是因为现在还没下发脚本，如果你不想要这个提示的话你在APPdelegate把环境配置换成生产环境。如图：
![image](https://cloud.githubusercontent.com/assets/13587915/23152556/c3e7c674-f83d-11e6-9211-03ba4743f81d.png)
如果你想自己测试的话，你自己写一个main.js脚本，然后直接放到工程，再把APPdelegate把环境配置换成测试环境。

**Comment by BinBear** [comment]
@MansionWayh 01：生产环境    00：测试环境
