### ISSUE TITLE
你好, 请问所有的网络请求都要写进HTViewModelProtocolImpl 这个协议吗

### ISSUE THREAD

**Issue by GCIOS** [BinBear/breadtrip-ReactiveCocoa-MVVM-#3]
比如说以后要是增加 获得评论接口,发送评论接口, 收藏接口...都要在HTViewModelProtocolImpl 这个协议写吗?

**Comment by BinBear** [comment]
@GCIOS 对的

**Comment by GCIOS** [comment]
好的，谢谢

发自我的 iPhone

**Comment by tangzzz-fan** [comment]
@BinBear 你好, 我问一下, 这里使用 HTViewModelProtocolImpl 这个协议来集束 APP 里的网络接口 (@optional), 有什么好处吗? 另外在进行 两个 ViewModel 之间的跳转时, 使用的是: [[HTViewModelServicesImpl alloc] initModelServiceImpl]; 这样每次创建了一个新的 总线? (可能并没有创建新的总线), 为什么要这样做? 为什么不使用一个单例类型的总线?
没有找到你的联系方式, 所以在这里发了, 不好意思

**Comment by BinBear** [comment]
@tangzzz-fan 使用 HTViewModelProtocolImpl来集约所有的接口是为了方便管理，这样可以避免每个新接口都要创建一个协议，不会让接口散落在各个地方。至于每次都创建一个新的ServiceImpl服务，没有使用单例的原因是为了以后能做扩展

**Comment by tangzzz-fan** [comment]
多谢, 多谢

**Comment by CeaserW** [comment]
你好，很感谢你的分享。有几个疑问1.感觉这个类HTViewModelServicesImpl已经和所有的service耦合了，为什么不直接实现方法用来getservice还要遵守HTViewModelService 这个协议，有什么好处吗？
2， HTViewModelServicesImpl这个类每次创建的时候 都会创建所有的service 创建service的方法 可以写在getservice方法里面吗？
