### ISSUE TITLE
你好，还有个疑问，就是结合 mj_ 上拉时， 我看到信号里面 赋值直接是 self.travelData = result[TravelDatakey];  以前习惯上拉加载更多时都是加到原来的数据源里面，这里面做了什么处理了吗，这里怎么感觉直接取最新请求到的数据呢？

### ISSUE THREAD

**Issue by CNDEVE** [BinBear/breadtrip-ReactiveCocoa-MVVM-#6]

**Comment by BinBear** [comment]
@BruceWee01 仔细看一下代码，加载更多是就是加到原来的数据源，并不是刷新最新的数据
![image](https://user-images.githubusercontent.com/13587915/29598259-596328a0-87fa-11e7-98f9-cc87c199d95c.png)

**Comment by CNDEVE** [comment]
后来才看到 谢谢！
