### ISSUE TITLE
请问，可否尽快实现 HTCityTravelDetialViewModel ？

### ISSUE THREAD

**Issue by bravelyfromdesire** [BinBear/breadtrip-ReactiveCocoa-MVVM-#8]
你好，我们打算使用你的APP做一个Demo，请问能不能尽快实现 HTCityTravelDetialViewModel ？

**Comment by BinBear** [comment]
@bravelyfromdesire 最近公司项目比较忙，之后有时间再说吧

**Comment by bravelyfromdesire** [comment]
OK :-)

**Comment by bravelyfromdesire** [comment]
你好，付费完成后续的开发，有商量吗？

**Comment by BinBear** [comment]
@bravelyfromdesire 为啥要付费完成后续开发啊，你很需要后面的代码？

**Comment by bravelyfromdesire** [comment]
没事，这个不是问题了。我现在想请教一下启动图片怎么修改？我尝试了很多办法，效果都不好。我希望尽量简单点：找到图片的位置，然后替换。

**Comment by lvxiangan** [comment]
期待后续更新
